[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"

[dev]
  framework = "html"
  targetPort = 3000
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
